In [2]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [5]:
arr  = np.array(my_list)

In [8]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [15]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [16]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [17]:
arr = np.arange(0,11)

In [18]:
arr[8]

8

In [19]:
arr[1:5]

array([1, 2, 3, 4])